### ISSUE TITLE
Mejoras para Jumbotron

### ISSUE THREAD

**Issue by hchocobar** [4GeeksAcademy/spain44-g2-landing-page-with-react#20]
Muy buen texto en el Jumbotron!!!! 

Podrían darle un mejor formato insertando h2 y parrafos para que no se vea como un solo texto muy largo

- [x] Insertar subtitulos
- [x] Insertar párrafos

**Comment by OconnelDan** [comment]
Insertados subtitulo y parrafos. En la rama DanielH-landingPage-Jumbotron-DanielH

**Comment by hchocobar** [comment]
Genial, gracias Daniel
